### ISSUE TITLE
Getting a modules adress.

### ISSUE THREAD

**Issue by lhaasper** [CasualCoder91/CasualLibrary#2]
So I am making an external for csgo... to basically get anything (for example health) I need to do:
(adress of the client.dll module) + playerBase + offset of whatever.. (health for example)

For some reason it returns 0 if I do: 
Address clientadr = external.getModule("client.dll");

and then cout << "Health: " << external.read<float>(clientadr + playerBase + 0x2FC8) << std::endl;

Thanks :D

**Comment by ChefZander** [comment]
That's bc there is no client.dll in CSGO (i think it is panorama.dll or sth you have to look it up)

**Comment by 1hAck-0** [comment]
"client.dll" is correct, but you can't just add the offset (0x2FC8) like that, you should first get the address at clientadr + playerBase, then add to that address 0x2FC8 and it should work.



Address clientadr = external.getModule("client.dll");
cout << "Health: " << external.read(external.read(clientadr + playerBase) + 0x2FC8) << std::endl;

**Comment by CasualCoder91** [comment]
> Address clientadr = external.getModule("client.dll"); cout << "Health: " << external.read(external.read(clientadr + playerBase) + 0x2FC8) << std::endl;

Thank you. Yes this is one option. Or you could also do:
external.getAddress(clientadr + playerBase, { 0x2FC8 }).get();
